### ISSUE TITLE
USER STORY: Manage a poll for project 1:Wu Zetian

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/My-agile-project-1#5]
As a **administrator ** I can **create a poll for my project 1**  so that **user feedback**

# Acceptance criteria:

+ Acceptance criteria 1: The poll should only run one day, finish at 12pm
- Acceptance criteria 2: The options  in the poll , provided as a checkbox
* Acceptance criteria 3: The options should appear above the submit button

# Tasks:

- [ ] Task 1: update the poll the design and show the first letter of user name
- [ ] Task 2: update the results and controller function
- [ ] Task 3: test functionality
