### ISSUE TITLE
USER STORY: Project 2 creating a visitors log

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/My-agile-project-1#6]
As a **creator** I can **create a visiting chart ** so that **measure the visitation of the page and in prove **

**#Acceptance Criteria:**
- Acceptance Criteria 1:  The chart should show different age bracket of visitation
+ Acceptance Criteria 2: The chart should be different color for each age group
*  Acceptance Criteria 3: The chart will look like a doughnut 

# Tasks:

- [ ] Task1: check the design (HTML and CSS) that it's displayed correctly 
- [ ] Task2: create a new field where all the age groups are displayed
- [ ] Task3: test functionality
