### ISSUE TITLE
USER STORY: Score board display

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/My-agile-project-1#7]
As a **creater/administrator**  I can **create a score board to display results**  so that **the user and opponent can see who is winning** 

# Acceptance Criteria :

- Acceptance Criteria 1: the display should be in a seperate window display
- Acceptance Criteria 2: the window should show the winnig score
- Acceptance Criteria 3: the window should appear after 5 rounds

# Tasks:

- [ ] fit the design(HTML and CSS) for the the view on desktop and phone
- [ ] create a new field where the name of the winner is displayed
- [ ] test the functionality of the display
